import {
  Sparkles,
  Brain,
  ShieldAlert,
  CheckCircle2,
} from "lucide-react";

export default function AIExplanation({ report }) {
  if (!report) return null;

  const reasons = report.risk?.reasons || [];

  return (
    <div className="rounded-3xl border border-slate-800 bg-slate-900 p-8 shadow-lg">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="rounded-xl bg-blue-500/10 p-3">
            <Sparkles className="text-blue-400" />
          </div>

          <div>
            <h2 className="text-2xl font-bold">
              AI Threat Analysis
            </h2>

            <p className="text-sm text-slate-400">
              Generated by SafeLink AI Engine
            </p>
          </div>
        </div>

        <span className="rounded-full bg-blue-500/20 px-3 py-1 text-xs font-semibold text-blue-400">
          AI Powered
        </span>
      </div>

      <div className="mt-8 grid grid-cols-2 gap-4">
        <div className="rounded-2xl border border-slate-800 bg-slate-800/40 p-4">
          <p className="text-xs uppercase tracking-wide text-slate-400">
            Risk Score
          </p>

          <h3 className="mt-2 text-3xl font-bold text-blue-400">
            {report.risk.score}/100
          </h3>
        </div>

        <div className="rounded-2xl border border-slate-800 bg-slate-800/40 p-4">
          <p className="text-xs uppercase tracking-wide text-slate-400">
            Risk Level
          </p>

          <h3 className="mt-2 text-3xl font-bold text-green-400">
            {report.risk.level}
          </h3>
        </div>
      </div>

      <div className="mt-8 rounded-2xl border border-slate-800 bg-slate-800/40 p-5">
        <div className="flex items-center gap-2">
          <Brain className="text-blue-400" size={20} />

          <h3 className="font-semibold">
            Executive Summary
          </h3>
        </div>

        <p className="mt-4 leading-7 text-slate-300">
          {report.ai.summary}
        </p>
      </div>

      <div className="mt-6 space-y-4">
        {reasons.map((reason) => (
          <Reason key={reason} text={reason} />
        ))}
      </div>

      <div className="mt-8 rounded-2xl border border-red-500/20 bg-red-500/10 p-4">
        <div className="flex items-center gap-3">
          <ShieldAlert className="text-red-400" />

          <p className="text-sm leading-6 text-slate-300">
            {report.ai.recommendation}
          </p>
        </div>
      </div>
    </div>
  );
}

function Reason({ text }) {
  return (
    <div className="flex items-center gap-3 rounded-xl border border-slate-800 bg-slate-800/30 p-4">
      <CheckCircle2 className="text-green-400" size={18} />

      <span className="text-slate-300">
        {text}
      </span>
    </div>
  );
}