import { Download } from "lucide-react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function DownloadReportButton({ report }) {
  if (!report) return null;

  const downloadPDF = () => {
    const doc = new jsPDF();

    // ===== Title =====
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text("SafeLink AI", 14, 18);

    doc.setFontSize(13);
    doc.setFont("helvetica", "normal");
    doc.text("Website Security Analysis Report", 14, 27);

    doc.setDrawColor(70, 130, 255);
    doc.line(14, 31, 195, 31);

    // ===== Overview =====
    // ===== Overview =====
autoTable(doc, {
  startY: 38,
  theme: "grid",
  headStyles: {
    fillColor: [37, 99, 235],
    textColor: 255,
    fontStyle: "bold",
  },
  body: [
    ["Website", report.normalized_url || report.url || "N/A"],
    ["Risk Level", report.risk?.level || "Unknown"],
    ["Risk Score", `${report.risk?.score ?? 0}/100`],
    ["Scan Time", new Date().toLocaleString()],
  ],
});
const risk = (report.risk?.level || "UNKNOWN").toUpperCase();

let badgeColor = [34, 197, 94]; // Green

if (risk === "MEDIUM") {
  badgeColor = [245, 158, 11]; // Yellow
}

if (risk === "HIGH") {
  badgeColor = [239, 68, 68]; // Red
}

const y = doc.lastAutoTable.finalY + 10;

// Risk Badge
doc.setFillColor(...badgeColor);
doc.roundedRect(14, y, 40, 10, 2, 2, "F");
doc.setTextColor(255);
doc.setFontSize(11);
doc.setFont("helvetica", "bold");
doc.text(risk, 25, y + 7);

// Threat Score Badge
doc.setFillColor(59, 130, 246);
doc.roundedRect(65, y, 50, 10, 2, 2, "F");
doc.text(
  `${report.risk?.score ?? 0}/100`,
  78,
  y + 7
);

// Reset text color
doc.setTextColor(0);
    // ===== SSL =====
    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 8,
      head: [["SSL Information", ""]],
headStyles: {
  fillColor: [37, 99, 235],
  textColor: 255,
  fontStyle: "bold",
},
      body: [
        ["Status", report.ssl?.valid ? "Valid" : "Invalid"],
        ["Issuer", report.ssl?.issuer || "N/A"],
        ["Issued To", report.ssl?.issued_to || "N/A"],
        ["Expires", report.ssl?.expires || "N/A"],
      ],
    });

    // ===== Domain =====
    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 8,
      head: [["Domain Information", ""]],
      body: [
        ["Registrar", report.whois?.registrar || "N/A"],
        [
          "Domain Age",
          `${report.whois?.domain_age_years ?? "Unknown"} Years`,
        ],
        ["Country", report.whois?.country || "N/A"],
      ],
    });

    // ===== VirusTotal =====
    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 8,
      head: [["VirusTotal", ""]],
      body: [
        ["Malicious", report.virustotal?.malicious ?? 0],
        ["Suspicious", report.virustotal?.suspicious ?? 0],
        ["Harmless", report.virustotal?.harmless ?? 0],
        ["Undetected", report.virustotal?.undetected ?? 0],
      ],
    });

    // ===== AI Summary =====
    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 8,
      head: [["AI Analysis"]],
      body: [[report.ai?.summary || "No summary available"]],
    });

    // ===== Recommendation =====
    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 8,
      head: [["Recommendation"]],
      body: [[report.ai?.recommendation || "No recommendation available"]],
    });

    // ===== Footer =====
    doc.setFontSize(10);
    doc.text(
      "Generated by SafeLink AI",
      14,
      doc.internal.pageSize.height - 10
    );

    const filename =
      (report.normalized_url || report.url || "report")
        .replace(/^https?:\/\//, "")
        .replace(/[^\w.-]/g, "_");

    doc.save(`SafeLink_Report_${filename}.pdf`);
  };

  return (
    <button
      onClick={downloadPDF}
      className="flex items-center gap-2 rounded-xl bg-blue-600 px-6 py-3 font-medium text-white transition hover:bg-blue-700"
    >
      <Download size={18} />
      Download Report
    </button>
  );
}